fname = input("input name of file: ")
fopen = open(fname)
ls = list()
for lines in fopen:
    lines = lines.rstrip()
    #print(lines)
    stuff = lines.split()
    #print(stuff)
ls.append("Who")
ls.append("is")
ls.append("already")
ls.append("sick")
ls.append("and")
ls.append("pale")
ls.append("with")
ls.append("grief")
ls.append("It")
ls.append("the")
ls.append("east")
ls.append("Juliet")
ls.append("sun")
ls.append("Arise")
ls.append("fair")
ls.append("kill")
ls.append("envious")
ls.append("moon")
ls.append("But")
ls.append("soft")
ls.append("what")
ls.append("light")
ls.append("through")
ls.append("yonder")
ls.append("window")
ls.append("breaks")
#print(ls)
ls.sort()
print(ls)
